# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  major: '1'
  minor: '0'
  revision: $[counter(variables['minor'], 1)] # This will get reset every time minor gets bumped.
  nugetVersion: '$(major).$(minor).$(revision)'

steps:
- task: DotNetCoreCLI@2
  displayName: Nuget Restore
  inputs:
    command: 'restore'
    projects: '**/SG-Models.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Nuget Build
  inputs:
    command: 'build'
    projects: '**/SG-Models.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Nuget Package
  inputs:
    command: 'pack'
    packagesToPack: '**/SG-Models.csproj'
    versionEnvVar: 'nugetVersion'
    versioningScheme: 'byEnvVar'
- task: DotNetCoreCLI@2
  displayName: Nuget Push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2ae24e3e-b0fc-404f-a126-9910e4607375/b0b926d8-63d1-4ea0-96fd-84e1a31c8ead'


